[package]
name = "riffy"
version = "0.1.0"
authors = ["Bart Massey <bart.massey@gmail.com>"]
edition = "2018"

[dependencies.codepage-strings]
git = "https://github.com/BartMassey/codepage-strings"
branch = "main"
version = "0.1"
